FROM node:10-alpine

ENV SERVER_PORT 8080

# Move into a working directory
WORKDIR /usr/src/app

# Copy our package.json into the container. This tells npm about the
# module that we're trying to run
COPY package.json ./

# Let's install our dependencies
RUN npm install

# And now let's copy our code into the container
COPY . ./

# Execute our code when the continer starts up
EXPOSE $SERVER_PORT
CMD npm run server
